### PR TITLE
test using hhvm

### PR DESCRIPTION
**Pull request by ptarjan**
I marked it for allowing failures since I want see the problem so I can fix HHVM

### CODE REVIEW

**Comment by harikt** [comment]
Even if allow failure is marked, the travis flag was not green https://travis-ci.org/auraphp/Aura.SqlSchema.png?branch=develop-2 . ie why we removed the allow failure.

Sadly as the HHVM still fails at travis I don't think this will be merged .

**Comment by ptarjan** [comment]
@harikt It looks green to me, but I'm ok if we wait. I just put a fix into HHVM but we'll have to wait a few weeks for it to make it into release.

**Comment by harikt** [comment]
@ptarjan 

> It looks green to me

I was looking where I talked about this. Just noticed in Aura.Filter @pmjones has merged it https://github.com/auraphp/Aura.Filter/pull/36 ( I am still seeing it failed )

> but I'm ok if we wait

Please wait till @pmjones is back and he will get back to you.

> I just put a fix into HHVM but we'll have to wait a few weeks for it to make it into release.

Thank you. And happy to hear.

**Comment by harikt** [comment]
@ptarjan the version with fix was `HipHop VM 3.1.0 (rel)` , if so this is still failing in travis. I re run this see https://travis-ci.org/auraphp/Aura.SqlSchema/jobs/25580825

**Comment by ptarjan** [comment]
Sadly I don't think my fix made it into 3.1.0. Can you try with `hhvm-nightly`?

**Comment by harikt** [comment]
Hm, I was trying in travis. Sadly not installed hhvm 3+ in my system

**Comment by harikt** [comment]
We will wait @ptarjan . No problem. Thank you.

**Comment by ptarjan** [comment]
@harikt you can put `hhvm-nightly` instead of `hhvm` into your travis config and it will use the most recent code to make sure the fix I did actually fixes it for you.

**Comment by harikt** [comment]
Sorry still failing. https://travis-ci.org/auraphp/Aura.SqlSchema/jobs/25580825

**Comment by ptarjan** [comment]
@harikt that thing you linked to still has hhvm at version 3.1.0 so somehow the nightly thing didn't work.

**Comment by harikt** [comment]
may be it is not in the organization auraphp, next commit will trigger I assume

**Comment by harikt** [comment]
oh no hhvm is still failing https://travis-ci.org/auraphp/Aura.SqlSchema/jobs/28520812#L17 

``` bash
HipHop VM 3.2.0-dev+2014.06.26 (rel)
```

**Comment by ptarjan** [comment]
Ah, you're doing an exact string compare and we have 1 less indenting space than PHP. Is there any way you can normalize the space before comparing? (Maybe do a preg_replace('  ', '   ') if `defined(HHVM_VERSION)`.)

**Comment by harikt** [comment]
That seems we can fix with `assertEquals` probably. https://github.com/auraphp/Aura.SqlSchema/blob/0dbc07f4ecc4e7d1c52e13edf2e7cc7b34a8cddd/tests/src/ColumnTest.php#L65-L79

Thank you @ptarjan .

UPDATE : My bad `assertEquals` won't work. may be we need your fix. Could you open a fix so you are listed in out contributors section?  http://auraphp.com/contributors/

Else I will do it myself.

**Comment by harikt** [comment]
may be we close this in favour of #12

**Pull request closed without merging**
